<script>
export default {
  name: "Xword4",
  data() {
    return {
      xword: {
        id: 4,
        title: "Family Portrait",
        author: "Dustin Goldbarg",
        editor: "Dustin Goldbarg",
        createDate: "20150424",
        difficulty: 5,
        dimension: "15x15",
        theme:
          "All the **starred clues have a cheese hidden in their answer. 16-Across has 'CHEDDAR'," +
          " 57-Across has 'FONTINA', 3-Down has 'FETA', 8-Down has 'PARMESAN, 25-DOWN has 'GOAT' " +
          "and 22-DOWN has'EDAM'. It's called 'Family Portrait' because you traditionally say " +
          "'CHEESE' for the camera.",
        colorCells: [],
        shapeCells: [],
        numbering: [],
        solution: [
          "SIGN#GUTS#ACED#",
          "ERIU#REAP#RHEA#",
          "PARCHEDDARTERS#",
          "ANALOG##RUSE###",
          "LIFES#WOMB#SFSU",
          "##FISHEYE#NEONS",
          "TOE##SEESAW#ROE",
          "INT#FED#ANT#GRI",
          "TEA#GRAINS##OTT",
          "LAIRS#MATILDA##",
          "ELLA#BONA#EATME",
          "###PERU##SITTER",
          "#BITFONTINASIGN",
          "#ROOT#TACO#URAE",
          "#ANDS#SUET#NESS",
        ],
        clues: {
          across: {
            1: { txt: "Language for the hard of hearing" },
            5: { txt: "What the daring have" },
            9: { txt: "Didn't get a return" },
            13: { txt: "Irish Goddess" },
            14: { txt: "Realize, as benefits" },
            15: { txt: "Perlman, of 46-Across" },
            16: { txt: "**Thirsty runners" },
            19: { txt: "Like some clocks" },
            20: { txt: "Clever ploy" },
            21: { txt: "'_ a beach'" },
            22: { txt: "Your first home" },
            24: { txt: "West coast Univ." },
            28: { txt: "A certain lens" },
            30: { txt: "Some 1-Across's" },
            31: { txt: "Little piggy" },
            33: { txt: "Lever and fulcrum, essentially" },
            35: { txt: "Sushi topper" },
            36: { txt: "Sherman stat" },
            37: { txt: "_-Ex" },
            38: { txt: "Ends a ban?" },
            39: { txt: "Half of a descender?" },
            40: { txt: "Grey, black or green" },
            41: { txt: "Wheat and barley" },
            43: { txt: "Baseball Hall of Fame Mel" },
            44: { txt: "Burrows and tunnles" },
            46: { txt: "Telekinetic Dahl character" },
            49: { txt: "That latina" },
            50: { txt: "_ fide" },
            51: { txt: "Directions on Alice's cake" },
            54: { txt: "Lima's land" },
            56: { txt: "Comes with a house or baby" },
            57: { txt: "**Attention grabber" },
            61: { txt: "Type of beer or canal" },
            62: { txt: "_ Bell" },
            63: { txt: "World of Warcrafy site" },
            64: { txt: "Ifs & buts partner" },
            65: { txt: "Bird food" },
            66: { txt: "Loch of legend" },
          },
          down: {
            1: { txt: "Plant part" },
            2: { txt: "Mahmoud Ahmadinejad, for one" },
            3: { txt: "**Fly swatter" },
            4: { txt: "Atomic cores" },
            5: { txt: "Gumbel or Kinnear" },
            6: { txt: "It's in suede?" },
            7: { txt: "Iota" },
            8: { txt: "'**Let's get it on Kris'" },
            9: { txt: "Some Batchelors" },
            10: {
              txt:
                "It always makes you smile, and is hidden in this puzzles themed answers",
            },
            11: { txt: "Turns car into mechanic, e.g.?" },
            12: { txt: "Perp prosecuters" },
            17: { txt: "'Kick it, _'" },
            18: { txt: "It can be done the wrong way" },
            22: { txt: "**Nickle and dime" },
            23: { txt: "_ Como Va" },
            25: { txt: "**Be bare" },
            26: { txt: "Embarrassing laugh" },
            27: { txt: "'_ in a sentence'" },
            29: { txt: "Teen, briefly" },
            30: { txt: "Dre, E and Cube, together" },
            31: { txt: "Sir or madam" },
            32: { txt: "Laker great" },
            34: { txt: "Computing standards org." },
            37: { txt: "NFL 3-Pointers" },
            42: { txt: "McKellen of Mordor" },
            45: { txt: "Eminem is beginning to feel like one" },
            47: { txt: "50-Down kisser, a long time ago" },
            48: { txt: "Nissan, once" },
            50: { txt: "Certain sib" },
            52: { txt: "1 giga = 1024 _" },
            53: { txt: "Seahawks" },
            55: { txt: "Young newts" },
            56: { txt: "It might stuff you up" },
            57: { txt: "Cups you drank from, once" },
            58: { txt: "End to stat or edit" },
            59: { txt: "19th Greek letter" },
            60: { txt: "Clinch as a victory" },
          },
        },
      },
    };
  },
};
</script>
