<script>
export default {
  name: "Xword5",
  data() {
    return {
      xword: {
        id: 5,
        title: "B.W.S.T. - 3 ",
        author: "Dustin Goldbarg",
        editor: "Dustin Goldbarg",
        createDate: "20151215",
        difficulty: 5,
        dimension: "15x15",
        theme:
          "Each circled cell has a family word in it. The intersection of 17-Across and 4-Down is 'SIS'," +
          "the intersection of 25-Across asnd 11-Down is 'MOM', the intersection of 45-Across and 33-Down is 'DAD'" +
          ", and the intersection of 58-Across and 55-Down is 'BRO'",
        colorCells: [],
        shapeCells: [
          [2, 4, "circle"],
          [4, 12, "circle"],
          [10, 2, "circle"],
          [12, 10, "circle"],
        ],
        numbering: [],
        solution: [
          "IPA#AROMA#BATHS",
          "TAS#SERON#ADHOC",
          "ELLI|SIS|LAND#SIETE",
          "MEANT#CDR#EER##",
          "SONG#SLOE#SU|MOM|AT",
          "###RATE#TNT#ESE",
          "##LAVA#STU#STIX",
          "#FAMILYCIRCLES#",
          "ARMS#LEI#SOAR##",
          "SIB#OSS#DEPP###",
          "HO|DAD|DY#WEED#YAPS",
          "##EES#ELM#AORTA",
          "EFLAT#CLIM|BRO|UTES",
          "MATRE#ATSEA#ERS",
          "STAIR#NOEND#SOY",
        ],
        clues: {
          across: {
            1: { txt: "Potent potable" },
            4: { txt: "1-Across attractive attribute" },
            9: { txt: "Home to some ducks" },
            14: { txt: "Prof.'s prot\xE9g\xE9s" },
            15: { txt: "First town built after the Great Flood" },
            16: { txt: "On the fly" },
            17: { txt: "Destination for many travelers from oversees" },
            19: { txt: "Numero de mares" },
            20: { txt: "Intended" },
            21: { txt: "It can be burned, briefly" },
            22: { txt: "Heard at the end of an auction?" },
            23: { txt: "Dance partner?" },
            24: { txt: "_ gin fizz" },
            25: { txt: "Heavyweight wrestling locale" },
            28: { txt: "Going _" },
            30: { txt: "Acme Corp. best seller" },
            32: { txt: "Linguist's suffix" },
            33: { txt: "Etna ooze" },
            34: { txt: "Alphabet trio that is also a man's name" },
            35: { txt: "'Mr. Roboto' band" },
            36: { txt: "Intimite groups...or a hint to this puzzle's theme" },
            39: { txt: "Up in _ (outraged)" },
            40: { txt: "Island accessory" },
            41: { txt: "Get high, in a way" },
            42: { txt: "Cousin of 5-Down?" },
            43: { txt: "W.W.II agency" },
            44: { txt: "Director Burton's lead, often" },
            45: { txt: "Wavecatcher wannabee" },
            47: { txt: "It gets you high, in a different way" },
            49: { txt: "Goes on and on" },
            53: { txt: "Post-interview letters?" },
            54: { txt: "5-Down of 39-Down" },
            55: { txt: "It pumps you up" },
            56: { txt: "D-Sharp, sometimes" },
            58: { txt: "Get high, in even still another way" },
            60: { txt: "Latin mother" },
            61: { txt: "Cruising, e.g." },
            62: { txt: "Body shops, briefly?" },
            63: { txt: "Flight attendant?" },
            64: { txt: "To _ (ongoing)" },
            65: { txt: "Kind of sauce or bean" },
          },
          down: {
            1: { txt: "Tabloid topics" },
            2: { txt: "Trendy diet" },
            3: { txt: "C.S. Lewis lion" },
            4: { txt: "1/30th a triple-double" },
            5: { txt: "Cousin of 42-Across?" },
            6: { txt: "Fortune cookie?" },
            7: { txt: "Huge, to a 45-Across perhaps" },
            8: { txt: "Mario karter" },
            9: { txt: "Lowest of the low" },
            10: { txt: "'Farwell, Fifi'" },
            11: { txt: "It's usually room temperature" },
            12: { txt: "'You're close!'" },
            13: { txt: "Viscera guts?" },
            18: { txt: "Saint Mark, and others" },
            24: { txt: "Filibusters, say" },
            26: { txt: "Tan and Adams" },
            27: { txt: "Rangers, on a scoreboard" },
            29: { txt: "Beginning of some flying objects" },
            31: { txt: "Took one's time, as with a 1-Across" },
            33: { txt: "450, to Aristotle" },
            34: { txt: "Poli-_" },
            35: { txt: "'I will _ silly!'" },
            36: { txt: "Cold, to Carlos" },
            37: { txt: "2008 campaign line" },
            38: { txt: "Cruiser in a cruiser" },
            39: { txt: "5-Down of a 54-Across" },
            43: { txt: "The world, for some" },
            44: { txt: "Passing" },
            46: { txt: "'Frankly, my _...'" },
            48: { txt: "'1_ 1.143 meters' (cubit conversion)" },
            50: { txt: "M\xFAsica, et al." },
            51: { txt: "Beginning of some flying objects" },
            52: { txt: "Fresh" },
            55: { txt: "One way to study" },
            56: { txt: "Middle of summer?" },
            57: { txt: "It can be burned" },
            59: { txt: "United States presidents, e.g." },
          },
        },
      },
    };
  },
};
</script>
