<script>
export default {
  name: "Xword2",
  data() {
    return {
      xword: {
        id: 2,
        title: "B.W.S.T - 12",
        author: "Dustin Goldbarg",
        editor: "Dustin Goldbarg",
        createDate: "20180429",
        difficulty: 7,
        dimension: "21x21",
        theme:
          "Each asterisked clue is two famous band names next to eachother",
        colorCells: [],
        shapeCells: [],
        numbering: [],
        solution: [
          "#AIDA###BABA##AMT#CTO",
          "ATPAR#STIRUP##PIESHOP",
          "FRANC#TREETOP#INSPITE",
          "RISEAGAINSTTHEPOLICE#",
          "###SDAK####HOT#RAN###",
          "PET#EGEST#SENOR##MOM#",
          "SCUFF#SUBLIMENIRVANA#",
          "ACTIII#ZAGS###NIAGARA",
          "#OUTRE#YRS#DRAGON#MIX",
          "###FERB###MAORI#IRANI",
          "ASGOD#YELLOKORN#LACES",
          "SPIRO#ROMAN###GALS###",
          "TOV#ORIENT#VAN#SATAT#",
          "AREARUG###SIRI#PIETAS",
          "#KISSTHEANIMALS#CREPE",
          "#SNO##TALON#LEONE#MEN",
          "###CAB#SOM####RECT###",
          "#POISONTHECRANBERRIES",
          "RETAILS#ARIADNE#EATIT",
          "TOOLATE##CACHET#ADINS",
          "ENE#NSC##YOED###MESS#"
        ],
        clues: {
          across: {
            1: { txt: "Enslaved Ethiopian in Egypt" },
            5: { txt: "AMZN adversary" },
            9: { txt: "Lb., e.g." },
            12: { txt: "HBO's Hendricks, while working with Barkar" },
            15: { txt: "Face-valued as a bond" },
            16: { txt: "Evoke, as emotions" },
            18: { txt: "Joint filled with crust?" },
            20: { txt: "Euro predecessor" },
            21: { txt: "Certain star site" },
            23: { txt: "Regardless (of)" },
            24: { txt: "**What an angry mob might do" },
            27: { txt: "Where some presidents got stoned?: abbr." },
            28: { txt: "A 10, say" },
            29: { txt: "Amassed, as a tab" },
            30: { txt: "Chia __" },
            33: { txt: "Discharge" },
            36: { txt: "Hombre" },
            38: { txt: 'One who might respond to "5-Across"?' },
            41: { txt: "Mark" },
            43: { txt: "**Ultimate prefection" },
            47: { txt: "When 1-Across plans her escape" },
            49: { txt: "Bulldogs, to some" },
            50: { txt: "Big falls?" },
            52: { txt: "Odd" },
            53: { txt: "Sr. and Jr. e.g." },
            54: { txt: "Snap or fly accompanier" },
            57: {
              txt:
                "With 83-Down, compilation...or what you might find the answer to each starred clue written on"
            },
            58: { txt: "Fletcher, friend of Phineas Flynn" },
            60: { txt: "Zoolander tribesman race" },
            61: { txt: "Like Mahmoud Ahmadinejad" },
            63: { txt: "__ is my witness!" },
            66: { txt: "**America's largest cash crop?" },
            70: { txt: "Increases the potency as a drink" },
            71: { txt: "Politician Agnew" },
            72: { txt: "Like the characters in the second half of 47-Across" },
            73: { txt: "36-Down and 38-Across, e.g." },
            75: { txt: "Mozel __" },
            76: { txt: "Get ones bearings" },
            78: { txt: "Dutch surname starter" },
            81: { txt: "Occupied, as a table" },
            84: { txt: "It reall tied The Dude's room together" },
            86: { txt: "Modern personal assistant" },
            87: { txt: "Some Russian pieces" },
            89: { txt: "**Something you shouldn't do at a petting zoo?" },
            94: { txt: "Sweet or savory brunch option" },
            95: { txt: "Lead-in to Cone or Cat" },
            96: { txt: "Raptor weapon" },
            97: { txt: "Sierra __" },
            99: { txt: 'Aussie rockers, "__ at work"' },
            100: { txt: "Hailed thing" },
            103: { txt: "Its located in 90-Down 15-Down" },
            104: { txt: "Angle start" },
            106: { txt: "**Evil thing to do on Thanksgiving" },
            116: { txt: "Goes (for), as consumer goods" },
            117: { txt: "Page part" },
            118: { txt: "Wipe out" },
            119: { txt: '"That ship has sailed"' },
            120: { txt: "Prestige" },
            121: { txt: "Post deuce scores" },
            122: { txt: "Suffix with ethyl or propyl" },
            123: { txt: "CIA overseers" },
            124: { txt: "Walked the dog, say, collioquially" },
            125: { txt: "Screw (up)" }
          },
          down: {
            1: { txt: 'Longfellow\'s "The Bell of __"' },
            2: { txt: "Tap list section" },
            3: { txt: "Captain Cook, adn others" },
            4: { txt: "**Emergency exits when coin-ops combust?" },
            5: { txt: "Good, to a 36-Across" },
            6: { txt: "Greek god of war" },
            7: { txt: "Caboose" },
            8: {
              txt:
                "Marsupial with a speech impediment that always formss a right angle"
            },
            9: { txt: "Snake eye" },
            10: { txt: "Word with league or scale" },
            11: { txt: "Elon's enterprise" },
            12: { txt: "Smart" },
            13: { txt: "Bag that's often given away" },
            14: { txt: "Ajar, to a bard" },
            15: { txt: "Its 1st alphabetically, but worst economically" },
            16: { txt: "Asserts ownership of, as a claim" },
            17: { txt: "Angle start" },
            19: { txt: "Certain music publication, familiarly" },
            22: { txt: "Line or mega go-with" },
            25: { txt: "bit" },
            26: { txt: "Bond school" },
            30: { txt: '"Don\'t drink and drive", for one' },
            31: { txt: '"__ la Primavera", Landini piece' },
            32: { txt: "Portman or Kunis costume item" },
            34: { txt: "ESPN Sportscaster Kolber" },
            35: { txt: "Ski lift type" },
            36: { txt: 'Bradbury anthology, "__ for Space"' },
            37: { txt: "Trying, as with a 22-Down" },
            39: { txt: "Where you can stay dry while surfin Mavericks?" },
            40: { txt: "__ Corpse" },
            42: { txt: '"__ a king"' },
            44: { txt: "Some 22-Downs" },
            45: { txt: "80-Down, for one, to a 36-Across" },
            46: { txt: "**Certain cone contents" },
            48: { txt: "Front end" },
            51: { txt: "Allies adversaries" },
            54: { txt: "Cowboy Prescott" },
            55: { txt: "Pooh's pal" },
            56: { txt: "Touchdown time: abbr." },
            59: { txt: '"In fairness..."' },
            60: { txt: "Start to soon?" },
            62: { txt: "Vector alternative, in graphics" },
            63: { txt: "Thirties TV Terrier" },
            64: { txt: "Stappers and scoopers" },
            65: { txt: "Say Uncle" },
            67: { txt: "Job listing ltrs." },
            68: { txt: 'What is often said after "JK"' },
            69: { txt: "Not long" },
            74: { txt: "80-Down danger" },
            77: { txt: "Repentive routine" },
            78: { txt: "Liveliness" },
            79: { txt: "Certain shrinkin sea" },
            80: { txt: "Setting for 47-Across of 1-Across" },
            82: { txt: 'Fighting words, "Lemme __"' },
            83: { txt: "See 57-Across" },
            85: { txt: "Like a lone wolf" },
            86: { txt: 'Willis film "__ City"' },
            88: { txt: "1/100 on the Hill" },
            90: { txt: 'The "E" in 112-Down' },
            91: { txt: "Hello; Goodbye" },
            92: { txt: 'Don\'t go easy on, with "show"' },
            93: { txt: "46-Down alternative" },
            98: { txt: "Previously named" },
            101: { txt: "Of the 76-Across" },
            102: { txt: "Nuts' partner" },
            105: { txt: "Craft" },
            106: { txt: "Lowly laborer" },
            107: { txt: "Central Plains people" },
            108: { txt: "Little bit of time" },
            109: { txt: '"Adios"' },
            110: { txt: "Relay or drag" },
            111: { txt: "Ritalin target" },
            112: { txt: "Austin-to-Dallas dir." },
            113: { txt: "It's it's?" },
            114: { txt: "Drei zwei _" },
            115: { txt: "Pat and Nick, for two" },
            116: { txt: "66, e.g." }
          }
        }
      }
    };
  }
};
</script>
